/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nonconformingclient;

import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import noncormicommon.RMICommon;
import noncormicommon.RmiInterface;
import noncormicommon.NonCon;
/**
 *
 * @author mkaplan
 */
public class MainPage extends javax.swing.JPanel {
    public RmiInterface in;
    public RMICommon common;
    
public NonConf nonConf;
public ClientSide clientSide;
    /**
     * Creates new form MainPage
     */
    public MainPage(RmiInterface in) throws RemoteException, ClassNotFoundException, SQLException {
        initComponents();
        this.setVisible(true);
        this.in=in;
        viewT();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Şikayet Numarası", "Stok Kodu", "Şikayet Tarihi", "Talep Eden", "Birim Yetkilisi"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Tüm Uygunsuzluklar");

        jButton1.setText("Açık Uygunsuzluklar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Kapanan Uygunsuzluklar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addGap(263, 263, 263))
            .addGroup(layout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jLabel1.setText("Açık Uygunsuzluklar");
        try {
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            viewA();
        } catch (RemoteException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jLabel1.setText("Kapanmış Uygunsuzluklar");
        try {
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            viewK();
        } catch (RemoteException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
public void viewT() throws RemoteException, ClassNotFoundException, SQLException{
        ArrayList<NonCon> sikayetler = in.NCGetTum(common);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object [] row = new Object [5];
        for(int i=0; i<sikayetler.size();i++){
            row[0]=sikayetler.get(i).getNonConId();
            row[1]=sikayetler.get(i).getNonConProduct();
            row[2]=sikayetler.get(i).getNonConSDate();
            row[3]=sikayetler.get(i).getRequesterId();
            row[4]=sikayetler.get(i).getChefId();

            
            model.addRow(row);
            
        }}
            public void viewA() throws RemoteException, ClassNotFoundException, SQLException{
        ArrayList<NonCon> sikayetler = in.NCGet(common);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object [] row = new Object [5];
        for(int i=0; i<sikayetler.size();i++){
            row[0]=sikayetler.get(i).getNonConId();
            row[1]=sikayetler.get(i).getNonConProduct();
            row[2]=sikayetler.get(i).getNonConSDate();
            row[3]=sikayetler.get(i).getRequesterId();
            row[4]=sikayetler.get(i).getChefId();

            
            model.addRow(row);
            
        }}
             public void viewK() throws RemoteException, ClassNotFoundException, SQLException{
        ArrayList<NonCon> sikayetler = in.NCGetKapali(common);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object [] row = new Object [5];
        for(int i=0; i<sikayetler.size();i++){
            row[0]=sikayetler.get(i).getNonConId();
            row[1]=sikayetler.get(i).getNonConProduct();
            row[2]=sikayetler.get(i).getNonConSDate();
            row[3]=sikayetler.get(i).getRequesterId();
            row[4]=sikayetler.get(i).getChefId();

            
            model.addRow(row);
            
        }}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
